server:
  port: 10002

spring:
  application:
    name: order
  cloud:
    consul:
      host: 10.0.0.121
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
