server:
  port: 80

spring:
  application:
    name: gateway
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ssXXX
    serialization:
      indent_output: false
      fail_on_empty_beans: false
    defaultPropertyInclusion: NON_NULL
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
  cloud:
    consul:
      host: 10.0.0.121
      discovery:
        register: false
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
      - id: path_route
        uri: http://localhost:10002
        predicates:
          - Path=/order/**
        filters:
          - Authentication
          - RewritePath=/order/(.*), /api/order/$\1

feign:
  hystrix:
    enabled: true

management:
  endpoint:
    hystrix:
      stream:
        enabled: true

logging:
  level:
    root: info
    com.beyond.gateway: debug
